"""
This document has two purposes.
1. Integrate python with ngspice in order to parse a netlist in a pyfile
2. Use this to find the parameters of our coax cable based on the measured signal.
The netlist in question is in this folder under coax.cir.

TODO: Step 2. My idea is to simply run the file through scipy.optimize.root to
find the ideal values for the internal parts of the coax, but this will likely
be very slow.
"""

import subprocess
import tempfile
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# Parts of this script were generated by Claude 5.5.
import pandas as pd
from scipy.optimize import least_squares

# Circuit parameters (override the defaults in coax.cir via alterparam)
ZL = 50  # load impedance, ohm
INTRES = 0.05  # cable resistance, ohm per metre (50 m long)
MAXV = 1  # source amplitude, V
FREQ = 1e3  # sine frequency, Hz
PULSE = True  # True: pulse excitation, False: sine

try:
    HERE = Path(__file__).resolve().parent
except NameError:
    HERE = Path.cwd()
NETLIST = HERE / "coax.cir"

FIFTY = HERE / "test_data/20260928-0002_50Ohm/20260928-0002_50Ohm_02.csv"
df = pd.read_csv(FIFTY, skiprows=2, names=["time", "voltage"], dtype=float)
df.plot("time", "voltage")
DT = df["time"].diff().mean()
TSTOP = df["time"].iloc[-1]
TSTART = df["time"].iloc[0]


def runac(res, ind, cap):
    # Exactly one of the two series sources is active.
    sinamp, pulseamp = MAXV, 0
    # The line delay is ~250 ns, so a pulse needs ns resolution; a 1 kHz sine does not.
    tran = "tran 50u 2m"

    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        control = f"""
.control
set wr_singlescale
alterparam zl = {ZL}
alterparam intres = {res}
alterparam intind = {ind}
alterparam indcap = {cap}
alterparam sinamp = {sinamp}
alterparam pulseamp = {pulseamp}
alterparam freq = {FREQ}
alterparam td = {-TSTART}u
reset
ac dec 10 1 300meg
wrdata {d}/ac.txt v(2) v(23)
{tran}
wrdata {d}/tran.txt v(2) v(23)
.endc
.end
"""
        (d / "run.cir").write_text(NETLIST.read_text() + control)
        subprocess.run(
            ["ngspice", "-b", str(d / "run.cir")],
            check=True,
            capture_output=True,
            text=True,
        )
        tr = np.loadtxt(d / "tran.txt")  # time, v(2), v(23)
        ac = np.loadtxt(d / "ac.txt")  # freq, re(v2), im(v2), re(v23), im(v23)
    return ac, tr


def runpulse(res, ind, cap, length):
    """
    Run circuit simulation using a pulse signal. Coax is modelled as LTRA with res, ind, cap given by args.
    """
    # Exactly one of the two series sources is active.
    sinamp, pulseamp = 0, MAXV
    # The line delay is ~250 ns, so a pulse needs ns resolution; a 1 kHz sine does not.
    tran = f"tran {DT}u {TSTOP - TSTART}u"

    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        control = f"""
.control
set wr_singlescale
alterparam zl = {ZL}
alterparam intres = {res}
alterparam intind = {ind}
alterparam indcap = {cap}
alterparam coaxlen= {length}
alterparam sinamp = {sinamp}
alterparam pulseamp = {pulseamp}
alterparam freq = {FREQ}
alterparam td = {-TSTART}u
reset
{tran}
wrdata {d}/tran.txt v(2)
.endc
.end
"""
        (d / "run.cir").write_text(NETLIST.read_text() + control)
        subprocess.run(
            ["ngspice", "-b", str(d / "run.cir")],
            check=True,
            capture_output=True,
            text=True,
        )
        tr = np.loadtxt(d / "tran.txt")  # time, v(2), v(23)
        # ac = np.loadtxt(d / "ac.txt")  # freq, re(v2), im(v2), re(v23), im(v23)
    return tr


if __name__ == "__main__":
    tr = runpulse(INTRES, "0.38u", "67p", "50")

    def runpulsewrapper(arr: np.ndarray):
        print(arr)
        return runpulse(arr[0], str(arr[1]) + "u", str(arr[2]) + "p", arr[3])

    res, ind, cap, lng = least_squares(runpulsewrapper, np.array([0.05, 0.38, 67, 50]))

    # f = ac[:, 0]
    # v2 = ac[:, 1] + 1j * ac[:, 2]
    # v23 = ac[:, 3] + 1j * ac[:, 4]
    # h = v2 / v23  # replaces the old ".plot ac vp(2,23)"

    fig, a3 = plt.subplots(1, 1)
    # a1.semilogx(f, 20 * np.log10(abs(h)))
    # a1.set(xlabel="Hz", ylabel="|V(2)/V(23)| dB")
    # a2.semilogx(f, np.degrees(np.angle(h)))
    # a2.set(xlabel="Hz", ylabel="phase V(2) vs V(23) [deg]")
    a3.plot(tr[:, 0] * 1e6 + TSTART, tr[:, 1])
    a3.set(xlabel="µs", ylabel="V(2)")
    plt.tight_layout()
    plt.show()
