"""
This document has two purposes.
1. Integrate python with ngspice in order to parse a netlist in a pyfile
2. Use this to find the parameters of our coax cable based on the measured signal.
The netlist in question is in this folder under coax.cir.
"""

# This script was generated by Claude 5.5.
import subprocess
import tempfile
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

# Circuit parameters (override the defaults in coax.cir via alterparam)
ZL = 50  # load impedance, ohm
INTRES = 0.05  # cable resistance, ohm per metre (50 m long)
MAXV = 1  # source amplitude, V
FREQ = 1e3  # sine frequency, Hz
PULSE = True  # True: pulse excitation, False: sine

try:
    HERE = Path(__file__).resolve().parent
except NameError:
    HERE = Path.cwd()
NETLIST = HERE / "coax.cir"


def run():
    # Exactly one of the two series sources is active.
    sinamp, pulseamp = (0, MAXV) if PULSE else (MAXV, 0)
    # The line delay is ~250 ns, so a pulse needs ns resolution; a 1 kHz sine does not.
    tran = "tran 1n 3u" if PULSE else "tran 50u 2m"

    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        control = f"""
.control
set wr_singlescale
alterparam zl = {ZL}
alterparam intres = {INTRES}
alterparam sinamp = {sinamp}
alterparam pulseamp = {pulseamp}
alterparam freq = {FREQ}
reset
ac dec 10 1 300meg
wrdata {d}/ac.txt v(2) v(23)
{tran}
wrdata {d}/tran.txt v(2) v(23)
.endc
.end
"""
        (d / "run.cir").write_text(NETLIST.read_text() + control)
        subprocess.run(
            ["ngspice", "-b", str(d / "run.cir")],
            check=True,
            capture_output=True,
            text=True,
        )
        ac = np.loadtxt(d / "ac.txt")  # freq, re(v2), im(v2), re(v23), im(v23)
        tr = np.loadtxt(d / "tran.txt")  # time, v(2), v(23)
    return ac, tr


if __name__ == "__main__":
    ac, tr = run()

    f = ac[:, 0]
    v2 = ac[:, 1] + 1j * ac[:, 2]
    v23 = ac[:, 3] + 1j * ac[:, 4]
    h = v2 / v23  # replaces the old ".plot ac vp(2,23)"

    fig, (a1, a2, a3) = plt.subplots(3, 1, figsize=(8, 9))
    a1.semilogx(f, 20 * np.log10(abs(h)))
    a1.set(xlabel="Hz", ylabel="|V(2)/V(23)| dB")
    a2.semilogx(f, np.degrees(np.angle(h)))
    a2.set(xlabel="Hz", ylabel="phase V(2) vs V(23) [deg]")
    a3.plot(tr[:, 0] * 1e6, tr[:, 1])
    a3.set(xlabel="µs", ylabel="V(2)")
    plt.tight_layout()
    plt.show()
